// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file entity/ticket.entity.proto (package contract.tickets.entity, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { TicketStatus, TicketType } from "../enum/ticket.enum_pb";
import { file_enum_ticket_enum } from "../enum/ticket.enum_pb";
import type { LocationBuildType, LocationDormitoryType } from "../enum/location.enum_pb";
import { file_enum_location_enum } from "../enum/location.enum_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file entity/ticket.entity.proto.
 */
export const file_entity_ticket_entity: GenFile = /*@__PURE__*/
  fileDesc("ChplbnRpdHkvdGlja2V0LmVudGl0eS5wcm90bxIXY29udHJhY3QudGlja2V0cy5lbnRpdHkiywIKC1RpY2tldEJ1aWxkEgoKAmlkGAEgASgDEg8KB3VzZXJfaWQYAiABKAMSDAoEcm9vbRgDIAEoBRI6Cghsb2NhdGlvbhgEIAEoDjIoLmNvbnRyYWN0LnRpY2tldHMuZW51bS5Mb2NhdGlvbkJ1aWxkVHlwZRIPCgdjb21tZW50GAUgASgJEi8KBHR5cGUYBiABKA4yIS5jb250cmFjdC50aWNrZXRzLmVudW0uVGlja2V0VHlwZRIzCgZzdGF0dXMYByABKA4yIy5jb250cmFjdC50aWNrZXRzLmVudW0uVGlja2V0U3RhdHVzEi4KCnVwZGF0ZWRfYXQYCCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCmNyZWF0ZWRfYXQYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wItMCCg9UaWNrZXREb3JtaXRvcnkSCgoCaWQYASABKAMSDwoHdXNlcl9pZBgCIAEoAxIMCgRyb29tGAMgASgFEj4KCGxvY2F0aW9uGAQgASgOMiwuY29udHJhY3QudGlja2V0cy5lbnVtLkxvY2F0aW9uRG9ybWl0b3J5VHlwZRIPCgdjb21tZW50GAUgASgJEi8KBHR5cGUYBiABKA4yIS5jb250cmFjdC50aWNrZXRzLmVudW0uVGlja2V0VHlwZRIzCgZzdGF0dXMYByABKA4yIy5jb250cmFjdC50aWNrZXRzLmVudW0uVGlja2V0U3RhdHVzEi4KCnVwZGF0ZWRfYXQYCCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCmNyZWF0ZWRfYXQYCSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQtQBChtjb20uY29udHJhY3QudGlja2V0cy5lbnRpdHlCEVRpY2tldEVudGl0eVByb3RvUAFaJGR2Z211L3RpY2tldHMvY29udHJhY3QvZ2VuL2dvL2VudGl0eaICA0NURaoCF0NvbnRyYWN0LlRpY2tldHMuRW50aXR5ygIXQ29udHJhY3RcVGlja2V0c1xFbnRpdHniAiNDb250cmFjdFxUaWNrZXRzXEVudGl0eVxHUEJNZXRhZGF0YeoCGUNvbnRyYWN0OjpUaWNrZXRzOjpFbnRpdHliBnByb3RvMw", [file_google_protobuf_timestamp, file_enum_ticket_enum, file_enum_location_enum]);

/**
 * @generated from message contract.tickets.entity.TicketBuild
 */
export type TicketBuild = Message<"contract.tickets.entity.TicketBuild"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int64 user_id = 2;
   */
  userId: bigint;

  /**
   * @generated from field: int32 room = 3;
   */
  room: number;

  /**
   * @generated from field: contract.tickets.enum.LocationBuildType location = 4;
   */
  location: LocationBuildType;

  /**
   * @generated from field: string comment = 5;
   */
  comment: string;

  /**
   * @generated from field: contract.tickets.enum.TicketType type = 6;
   */
  type: TicketType;

  /**
   * @generated from field: contract.tickets.enum.TicketStatus status = 7;
   */
  status: TicketStatus;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 8;
   */
  updatedAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 9;
   */
  createdAt?: Timestamp | undefined;
};

/**
 * Describes the message contract.tickets.entity.TicketBuild.
 * Use `create(TicketBuildSchema)` to create a new message.
 */
export const TicketBuildSchema: GenMessage<TicketBuild> = /*@__PURE__*/
  messageDesc(file_entity_ticket_entity, 0);

/**
 * @generated from message contract.tickets.entity.TicketDormitory
 */
export type TicketDormitory = Message<"contract.tickets.entity.TicketDormitory"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int64 user_id = 2;
   */
  userId: bigint;

  /**
   * @generated from field: int32 room = 3;
   */
  room: number;

  /**
   * @generated from field: contract.tickets.enum.LocationDormitoryType location = 4;
   */
  location: LocationDormitoryType;

  /**
   * @generated from field: string comment = 5;
   */
  comment: string;

  /**
   * @generated from field: contract.tickets.enum.TicketType type = 6;
   */
  type: TicketType;

  /**
   * @generated from field: contract.tickets.enum.TicketStatus status = 7;
   */
  status: TicketStatus;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 8;
   */
  updatedAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 9;
   */
  createdAt?: Timestamp | undefined;
};

/**
 * Describes the message contract.tickets.entity.TicketDormitory.
 * Use `create(TicketDormitorySchema)` to create a new message.
 */
export const TicketDormitorySchema: GenMessage<TicketDormitory> = /*@__PURE__*/
  messageDesc(file_entity_ticket_entity, 1);

