// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file service/auth.service.proto (package contract.ver.service, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file service/auth.service.proto.
 */
export declare const file_service_auth_service: GenFile;

/**
 * @generated from message contract.ver.service.LoginRequest
 */
export declare type LoginRequest = Message<"contract.ver.service.LoginRequest"> & {
  /**
   * @generated from field: string password = 1;
   */
  password: string;
};

/**
 * Describes the message contract.ver.service.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export declare const LoginRequestSchema: GenMessage<LoginRequest>;

/**
 * @generated from message contract.ver.service.LoginResponse
 */
export declare type LoginResponse = Message<"contract.ver.service.LoginResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;

  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 2;
   */
  expiresAt?: Timestamp | undefined;
};

/**
 * Describes the message contract.ver.service.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export declare const LoginResponseSchema: GenMessage<LoginResponse>;

/**
 * @generated from message contract.ver.service.CheckRequest
 */
export declare type CheckRequest = Message<"contract.ver.service.CheckRequest"> & {
};

/**
 * Describes the message contract.ver.service.CheckRequest.
 * Use `create(CheckRequestSchema)` to create a new message.
 */
export declare const CheckRequestSchema: GenMessage<CheckRequest>;

/**
 * @generated from message contract.ver.service.CheckResponse
 */
export declare type CheckResponse = Message<"contract.ver.service.CheckResponse"> & {
  /**
   * @generated from field: google.protobuf.Timestamp expires_at = 1;
   */
  expiresAt?: Timestamp | undefined;
};

/**
 * Describes the message contract.ver.service.CheckResponse.
 * Use `create(CheckResponseSchema)` to create a new message.
 */
export declare const CheckResponseSchema: GenMessage<CheckResponse>;

/**
 * Temporary shared-password access. Login is the only public procedure;
 * every other RPC needs "Authorization: Bearer <token>".
 *
 * @generated from service contract.ver.service.AuthService
 */
export declare const AuthService: GenService<{
  /**
   * @generated from rpc contract.ver.service.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * Check succeeds only with a valid token — used by the UI to validate a stored session.
   *
   * @generated from rpc contract.ver.service.AuthService.Check
   */
  check: {
    methodKind: "unary";
    input: typeof CheckRequestSchema;
    output: typeof CheckResponseSchema;
  },
}>;

