// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file service/feedback.service.proto (package contract.ver.service, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { FeedbackAction, FeedbackStatus } from "../enum/feedback.enum_pb";
import type { Feedback } from "../entity/feedback.entity_pb";

/**
 * Describes the file service/feedback.service.proto.
 */
export declare const file_service_feedback_service: GenFile;

/**
 * All filters are optional. Newest feedback first.
 *
 * @generated from message contract.ver.service.FeedbackFetchRequest
 */
export declare type FeedbackFetchRequest = Message<"contract.ver.service.FeedbackFetchRequest"> & {
  /**
   * @generated from field: optional string site_slug = 1;
   */
  siteSlug?: string | undefined;

  /**
   * @generated from field: optional string version_id = 2;
   */
  versionId?: string | undefined;

  /**
   * @generated from field: optional contract.ver.enum.FeedbackStatus status = 3;
   */
  status?: FeedbackStatus | undefined;
};

/**
 * Describes the message contract.ver.service.FeedbackFetchRequest.
 * Use `create(FeedbackFetchRequestSchema)` to create a new message.
 */
export declare const FeedbackFetchRequestSchema: GenMessage<FeedbackFetchRequest>;

/**
 * @generated from message contract.ver.service.FeedbackFetchResponse
 */
export declare type FeedbackFetchResponse = Message<"contract.ver.service.FeedbackFetchResponse"> & {
  /**
   * @generated from field: repeated contract.ver.entity.Feedback feedbacks = 1;
   */
  feedbacks: Feedback[];
};

/**
 * Describes the message contract.ver.service.FeedbackFetchResponse.
 * Use `create(FeedbackFetchResponseSchema)` to create a new message.
 */
export declare const FeedbackFetchResponseSchema: GenMessage<FeedbackFetchResponse>;

/**
 * @generated from message contract.ver.service.FeedbackCreateRequest
 */
export declare type FeedbackCreateRequest = Message<"contract.ver.service.FeedbackCreateRequest"> & {
  /**
   * @generated from field: string site_slug = 1;
   */
  siteSlug: string;

  /**
   * @generated from field: string site_name = 2;
   */
  siteName: string;

  /**
   * @generated from field: string version_id = 3;
   */
  versionId: string;

  /**
   * @generated from field: string version_label = 4;
   */
  versionLabel: string;

  /**
   * @generated from field: string author_name = 5;
   */
  authorName: string;

  /**
   * @generated from field: string phone = 6;
   */
  phone: string;

  /**
   * @generated from field: contract.ver.enum.FeedbackAction action = 7;
   */
  action: FeedbackAction;

  /**
   * @generated from field: string comment = 8;
   */
  comment: string;
};

/**
 * Describes the message contract.ver.service.FeedbackCreateRequest.
 * Use `create(FeedbackCreateRequestSchema)` to create a new message.
 */
export declare const FeedbackCreateRequestSchema: GenMessage<FeedbackCreateRequest>;

/**
 * @generated from message contract.ver.service.FeedbackCreateResponse
 */
export declare type FeedbackCreateResponse = Message<"contract.ver.service.FeedbackCreateResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message contract.ver.service.FeedbackCreateResponse.
 * Use `create(FeedbackCreateResponseSchema)` to create a new message.
 */
export declare const FeedbackCreateResponseSchema: GenMessage<FeedbackCreateResponse>;

/**
 * @generated from message contract.ver.service.FeedbackChangeStatusRequest
 */
export declare type FeedbackChangeStatusRequest = Message<"contract.ver.service.FeedbackChangeStatusRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: contract.ver.enum.FeedbackStatus new_status = 2;
   */
  newStatus: FeedbackStatus;
};

/**
 * Describes the message contract.ver.service.FeedbackChangeStatusRequest.
 * Use `create(FeedbackChangeStatusRequestSchema)` to create a new message.
 */
export declare const FeedbackChangeStatusRequestSchema: GenMessage<FeedbackChangeStatusRequest>;

/**
 * @generated from message contract.ver.service.FeedbackChangeStatusResponse
 */
export declare type FeedbackChangeStatusResponse = Message<"contract.ver.service.FeedbackChangeStatusResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message contract.ver.service.FeedbackChangeStatusResponse.
 * Use `create(FeedbackChangeStatusResponseSchema)` to create a new message.
 */
export declare const FeedbackChangeStatusResponseSchema: GenMessage<FeedbackChangeStatusResponse>;

/**
 * @generated from service contract.ver.service.FeedbackService
 */
export declare const FeedbackService: GenService<{
  /**
   * @generated from rpc contract.ver.service.FeedbackService.FeedbackFetch
   */
  feedbackFetch: {
    methodKind: "unary";
    input: typeof FeedbackFetchRequestSchema;
    output: typeof FeedbackFetchResponseSchema;
  },
  /**
   * @generated from rpc contract.ver.service.FeedbackService.FeedbackCreate
   */
  feedbackCreate: {
    methodKind: "unary";
    input: typeof FeedbackCreateRequestSchema;
    output: typeof FeedbackCreateResponseSchema;
  },
  /**
   * @generated from rpc contract.ver.service.FeedbackService.FeedbackChangeStatus
   */
  feedbackChangeStatus: {
    methodKind: "unary";
    input: typeof FeedbackChangeStatusRequestSchema;
    output: typeof FeedbackChangeStatusResponseSchema;
  },
}>;

