// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file service/journal.service.proto (package contract.ver.service, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Journal, WorkEntry } from "../entity/journal.entity_pb";
import type { WorkCategory } from "../enum/journal.enum_pb";

/**
 * Describes the file service/journal.service.proto.
 */
export declare const file_service_journal_service: GenFile;

/**
 * @generated from message contract.ver.service.JournalListRequest
 */
export declare type JournalListRequest = Message<"contract.ver.service.JournalListRequest"> & {
};

/**
 * Describes the message contract.ver.service.JournalListRequest.
 * Use `create(JournalListRequestSchema)` to create a new message.
 */
export declare const JournalListRequestSchema: GenMessage<JournalListRequest>;

/**
 * @generated from message contract.ver.service.JournalListResponse
 */
export declare type JournalListResponse = Message<"contract.ver.service.JournalListResponse"> & {
  /**
   * @generated from field: repeated contract.ver.entity.Journal journals = 1;
   */
  journals: Journal[];
};

/**
 * Describes the message contract.ver.service.JournalListResponse.
 * Use `create(JournalListResponseSchema)` to create a new message.
 */
export declare const JournalListResponseSchema: GenMessage<JournalListResponse>;

/**
 * @generated from message contract.ver.service.JournalBySlugRequest
 */
export declare type JournalBySlugRequest = Message<"contract.ver.service.JournalBySlugRequest"> & {
  /**
   * @generated from field: string slug = 1;
   */
  slug: string;
};

/**
 * Describes the message contract.ver.service.JournalBySlugRequest.
 * Use `create(JournalBySlugRequestSchema)` to create a new message.
 */
export declare const JournalBySlugRequestSchema: GenMessage<JournalBySlugRequest>;

/**
 * @generated from message contract.ver.service.JournalBySlugResponse
 */
export declare type JournalBySlugResponse = Message<"contract.ver.service.JournalBySlugResponse"> & {
  /**
   * @generated from field: contract.ver.entity.Journal entity = 1;
   */
  entity?: Journal | undefined;
};

/**
 * Describes the message contract.ver.service.JournalBySlugResponse.
 * Use `create(JournalBySlugResponseSchema)` to create a new message.
 */
export declare const JournalBySlugResponseSchema: GenMessage<JournalBySlugResponse>;

/**
 * @generated from message contract.ver.service.JournalCreateRequest
 */
export declare type JournalCreateRequest = Message<"contract.ver.service.JournalCreateRequest"> & {
  /**
   * @generated from field: string slug = 1;
   */
  slug: string;

  /**
   * @generated from field: string employee = 2;
   */
  employee: string;

  /**
   * @generated from field: string role = 3;
   */
  role: string;
};

/**
 * Describes the message contract.ver.service.JournalCreateRequest.
 * Use `create(JournalCreateRequestSchema)` to create a new message.
 */
export declare const JournalCreateRequestSchema: GenMessage<JournalCreateRequest>;

/**
 * @generated from message contract.ver.service.JournalCreateResponse
 */
export declare type JournalCreateResponse = Message<"contract.ver.service.JournalCreateResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message contract.ver.service.JournalCreateResponse.
 * Use `create(JournalCreateResponseSchema)` to create a new message.
 */
export declare const JournalCreateResponseSchema: GenMessage<JournalCreateResponse>;

/**
 * All filters are optional; without journal_id entries of every journal are returned.
 *
 * @generated from message contract.ver.service.WorkEntryFetchRequest
 */
export declare type WorkEntryFetchRequest = Message<"contract.ver.service.WorkEntryFetchRequest"> & {
  /**
   * @generated from field: optional int64 journal_id = 1;
   */
  journalId?: bigint | undefined;

  /**
   * Inclusive ISO days, YYYY-MM-DD.
   *
   * @generated from field: optional string from_date = 2;
   */
  fromDate?: string | undefined;

  /**
   * @generated from field: optional string to_date = 3;
   */
  toDate?: string | undefined;

  /**
   * @generated from field: optional string site_slug = 4;
   */
  siteSlug?: string | undefined;

  /**
   * @generated from field: optional contract.ver.enum.WorkCategory category = 5;
   */
  category?: WorkCategory | undefined;
};

/**
 * Describes the message contract.ver.service.WorkEntryFetchRequest.
 * Use `create(WorkEntryFetchRequestSchema)` to create a new message.
 */
export declare const WorkEntryFetchRequestSchema: GenMessage<WorkEntryFetchRequest>;

/**
 * @generated from message contract.ver.service.WorkEntryFetchResponse
 */
export declare type WorkEntryFetchResponse = Message<"contract.ver.service.WorkEntryFetchResponse"> & {
  /**
   * @generated from field: repeated contract.ver.entity.WorkEntry entries = 1;
   */
  entries: WorkEntry[];
};

/**
 * Describes the message contract.ver.service.WorkEntryFetchResponse.
 * Use `create(WorkEntryFetchResponseSchema)` to create a new message.
 */
export declare const WorkEntryFetchResponseSchema: GenMessage<WorkEntryFetchResponse>;

/**
 * @generated from message contract.ver.service.WorkEntryCreateRequest
 */
export declare type WorkEntryCreateRequest = Message<"contract.ver.service.WorkEntryCreateRequest"> & {
  /**
   * @generated from field: int64 journal_id = 1;
   */
  journalId: bigint;

  /**
   * @generated from field: string date = 2;
   */
  date: string;

  /**
   * @generated from field: string site_slug = 3;
   */
  siteSlug: string;

  /**
   * @generated from field: contract.ver.enum.WorkCategory category = 4;
   */
  category: WorkCategory;

  /**
   * @generated from field: string title = 5;
   */
  title: string;

  /**
   * @generated from field: string details = 6;
   */
  details: string;

  /**
   * @generated from field: repeated string steps = 7;
   */
  steps: string[];

  /**
   * @generated from field: string result = 8;
   */
  result: string;

  /**
   * @generated from field: double hours = 9;
   */
  hours: number;
};

/**
 * Describes the message contract.ver.service.WorkEntryCreateRequest.
 * Use `create(WorkEntryCreateRequestSchema)` to create a new message.
 */
export declare const WorkEntryCreateRequestSchema: GenMessage<WorkEntryCreateRequest>;

/**
 * @generated from message contract.ver.service.WorkEntryCreateResponse
 */
export declare type WorkEntryCreateResponse = Message<"contract.ver.service.WorkEntryCreateResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message contract.ver.service.WorkEntryCreateResponse.
 * Use `create(WorkEntryCreateResponseSchema)` to create a new message.
 */
export declare const WorkEntryCreateResponseSchema: GenMessage<WorkEntryCreateResponse>;

/**
 * @generated from message contract.ver.service.WorkEntryUpdateRequest
 */
export declare type WorkEntryUpdateRequest = Message<"contract.ver.service.WorkEntryUpdateRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string date = 2;
   */
  date: string;

  /**
   * @generated from field: string site_slug = 3;
   */
  siteSlug: string;

  /**
   * @generated from field: contract.ver.enum.WorkCategory category = 4;
   */
  category: WorkCategory;

  /**
   * @generated from field: string title = 5;
   */
  title: string;

  /**
   * @generated from field: string details = 6;
   */
  details: string;

  /**
   * @generated from field: repeated string steps = 7;
   */
  steps: string[];

  /**
   * @generated from field: string result = 8;
   */
  result: string;

  /**
   * @generated from field: double hours = 9;
   */
  hours: number;
};

/**
 * Describes the message contract.ver.service.WorkEntryUpdateRequest.
 * Use `create(WorkEntryUpdateRequestSchema)` to create a new message.
 */
export declare const WorkEntryUpdateRequestSchema: GenMessage<WorkEntryUpdateRequest>;

/**
 * @generated from message contract.ver.service.WorkEntryUpdateResponse
 */
export declare type WorkEntryUpdateResponse = Message<"contract.ver.service.WorkEntryUpdateResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message contract.ver.service.WorkEntryUpdateResponse.
 * Use `create(WorkEntryUpdateResponseSchema)` to create a new message.
 */
export declare const WorkEntryUpdateResponseSchema: GenMessage<WorkEntryUpdateResponse>;

/**
 * @generated from message contract.ver.service.WorkEntryDeleteRequest
 */
export declare type WorkEntryDeleteRequest = Message<"contract.ver.service.WorkEntryDeleteRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message contract.ver.service.WorkEntryDeleteRequest.
 * Use `create(WorkEntryDeleteRequestSchema)` to create a new message.
 */
export declare const WorkEntryDeleteRequestSchema: GenMessage<WorkEntryDeleteRequest>;

/**
 * @generated from message contract.ver.service.WorkEntryDeleteResponse
 */
export declare type WorkEntryDeleteResponse = Message<"contract.ver.service.WorkEntryDeleteResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message contract.ver.service.WorkEntryDeleteResponse.
 * Use `create(WorkEntryDeleteResponseSchema)` to create a new message.
 */
export declare const WorkEntryDeleteResponseSchema: GenMessage<WorkEntryDeleteResponse>;

/**
 * @generated from service contract.ver.service.JournalService
 */
export declare const JournalService: GenService<{
  /**
   * @generated from rpc contract.ver.service.JournalService.JournalList
   */
  journalList: {
    methodKind: "unary";
    input: typeof JournalListRequestSchema;
    output: typeof JournalListResponseSchema;
  },
  /**
   * @generated from rpc contract.ver.service.JournalService.JournalBySlug
   */
  journalBySlug: {
    methodKind: "unary";
    input: typeof JournalBySlugRequestSchema;
    output: typeof JournalBySlugResponseSchema;
  },
  /**
   * @generated from rpc contract.ver.service.JournalService.JournalCreate
   */
  journalCreate: {
    methodKind: "unary";
    input: typeof JournalCreateRequestSchema;
    output: typeof JournalCreateResponseSchema;
  },
}>;

/**
 * @generated from service contract.ver.service.WorkEntryService
 */
export declare const WorkEntryService: GenService<{
  /**
   * @generated from rpc contract.ver.service.WorkEntryService.WorkEntryFetch
   */
  workEntryFetch: {
    methodKind: "unary";
    input: typeof WorkEntryFetchRequestSchema;
    output: typeof WorkEntryFetchResponseSchema;
  },
  /**
   * @generated from rpc contract.ver.service.WorkEntryService.WorkEntryCreate
   */
  workEntryCreate: {
    methodKind: "unary";
    input: typeof WorkEntryCreateRequestSchema;
    output: typeof WorkEntryCreateResponseSchema;
  },
  /**
   * @generated from rpc contract.ver.service.WorkEntryService.WorkEntryUpdate
   */
  workEntryUpdate: {
    methodKind: "unary";
    input: typeof WorkEntryUpdateRequestSchema;
    output: typeof WorkEntryUpdateResponseSchema;
  },
  /**
   * @generated from rpc contract.ver.service.WorkEntryService.WorkEntryDelete
   */
  workEntryDelete: {
    methodKind: "unary";
    input: typeof WorkEntryDeleteRequestSchema;
    output: typeof WorkEntryDeleteResponseSchema;
  },
}>;

