// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file service/scheme.service.proto (package contract.ver.service, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { SchemeStage } from "../entity/scheme.entity_pb";
import type { SchemeStageStatus } from "../enum/scheme.enum_pb";

/**
 * Describes the file service/scheme.service.proto.
 */
export declare const file_service_scheme_service: GenFile;

/**
 * Without scheme_id, stages of every scheme of the project are returned.
 * Ordered by due date (stages without one last), then by id.
 *
 * @generated from message contract.ver.service.SchemeStageFetchRequest
 */
export declare type SchemeStageFetchRequest = Message<"contract.ver.service.SchemeStageFetchRequest"> & {
  /**
   * @generated from field: string site_slug = 1;
   */
  siteSlug: string;

  /**
   * @generated from field: optional string scheme_id = 2;
   */
  schemeId?: string | undefined;
};

/**
 * Describes the message contract.ver.service.SchemeStageFetchRequest.
 * Use `create(SchemeStageFetchRequestSchema)` to create a new message.
 */
export declare const SchemeStageFetchRequestSchema: GenMessage<SchemeStageFetchRequest>;

/**
 * @generated from message contract.ver.service.SchemeStageFetchResponse
 */
export declare type SchemeStageFetchResponse = Message<"contract.ver.service.SchemeStageFetchResponse"> & {
  /**
   * @generated from field: repeated contract.ver.entity.SchemeStage stages = 1;
   */
  stages: SchemeStage[];
};

/**
 * Describes the message contract.ver.service.SchemeStageFetchResponse.
 * Use `create(SchemeStageFetchResponseSchema)` to create a new message.
 */
export declare const SchemeStageFetchResponseSchema: GenMessage<SchemeStageFetchResponse>;

/**
 * @generated from message contract.ver.service.SchemeStageCreateRequest
 */
export declare type SchemeStageCreateRequest = Message<"contract.ver.service.SchemeStageCreateRequest"> & {
  /**
   * @generated from field: string site_slug = 1;
   */
  siteSlug: string;

  /**
   * @generated from field: string scheme_id = 2;
   */
  schemeId: string;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: string details = 4;
   */
  details: string;

  /**
   * @generated from field: string start_date = 5;
   */
  startDate: string;

  /**
   * @generated from field: string due_date = 6;
   */
  dueDate: string;

  /**
   * @generated from field: contract.ver.enum.SchemeStageStatus status = 7;
   */
  status: SchemeStageStatus;
};

/**
 * Describes the message contract.ver.service.SchemeStageCreateRequest.
 * Use `create(SchemeStageCreateRequestSchema)` to create a new message.
 */
export declare const SchemeStageCreateRequestSchema: GenMessage<SchemeStageCreateRequest>;

/**
 * @generated from message contract.ver.service.SchemeStageCreateResponse
 */
export declare type SchemeStageCreateResponse = Message<"contract.ver.service.SchemeStageCreateResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message contract.ver.service.SchemeStageCreateResponse.
 * Use `create(SchemeStageCreateResponseSchema)` to create a new message.
 */
export declare const SchemeStageCreateResponseSchema: GenMessage<SchemeStageCreateResponse>;

/**
 * Replaces the stage's content; the project and scheme don't change.
 *
 * @generated from message contract.ver.service.SchemeStageUpdateRequest
 */
export declare type SchemeStageUpdateRequest = Message<"contract.ver.service.SchemeStageUpdateRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string details = 3;
   */
  details: string;

  /**
   * @generated from field: string start_date = 4;
   */
  startDate: string;

  /**
   * @generated from field: string due_date = 5;
   */
  dueDate: string;

  /**
   * @generated from field: contract.ver.enum.SchemeStageStatus status = 6;
   */
  status: SchemeStageStatus;
};

/**
 * Describes the message contract.ver.service.SchemeStageUpdateRequest.
 * Use `create(SchemeStageUpdateRequestSchema)` to create a new message.
 */
export declare const SchemeStageUpdateRequestSchema: GenMessage<SchemeStageUpdateRequest>;

/**
 * @generated from message contract.ver.service.SchemeStageUpdateResponse
 */
export declare type SchemeStageUpdateResponse = Message<"contract.ver.service.SchemeStageUpdateResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message contract.ver.service.SchemeStageUpdateResponse.
 * Use `create(SchemeStageUpdateResponseSchema)` to create a new message.
 */
export declare const SchemeStageUpdateResponseSchema: GenMessage<SchemeStageUpdateResponse>;

/**
 * @generated from message contract.ver.service.SchemeStageDeleteRequest
 */
export declare type SchemeStageDeleteRequest = Message<"contract.ver.service.SchemeStageDeleteRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message contract.ver.service.SchemeStageDeleteRequest.
 * Use `create(SchemeStageDeleteRequestSchema)` to create a new message.
 */
export declare const SchemeStageDeleteRequestSchema: GenMessage<SchemeStageDeleteRequest>;

/**
 * @generated from message contract.ver.service.SchemeStageDeleteResponse
 */
export declare type SchemeStageDeleteResponse = Message<"contract.ver.service.SchemeStageDeleteResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: bool success = 2;
   */
  success: boolean;

  /**
   * @generated from field: string message = 3;
   */
  message: string;
};

/**
 * Describes the message contract.ver.service.SchemeStageDeleteResponse.
 * Use `create(SchemeStageDeleteResponseSchema)` to create a new message.
 */
export declare const SchemeStageDeleteResponseSchema: GenMessage<SchemeStageDeleteResponse>;

/**
 * @generated from service contract.ver.service.SchemeStageService
 */
export declare const SchemeStageService: GenService<{
  /**
   * @generated from rpc contract.ver.service.SchemeStageService.SchemeStageFetch
   */
  schemeStageFetch: {
    methodKind: "unary";
    input: typeof SchemeStageFetchRequestSchema;
    output: typeof SchemeStageFetchResponseSchema;
  },
  /**
   * @generated from rpc contract.ver.service.SchemeStageService.SchemeStageCreate
   */
  schemeStageCreate: {
    methodKind: "unary";
    input: typeof SchemeStageCreateRequestSchema;
    output: typeof SchemeStageCreateResponseSchema;
  },
  /**
   * @generated from rpc contract.ver.service.SchemeStageService.SchemeStageUpdate
   */
  schemeStageUpdate: {
    methodKind: "unary";
    input: typeof SchemeStageUpdateRequestSchema;
    output: typeof SchemeStageUpdateResponseSchema;
  },
  /**
   * @generated from rpc contract.ver.service.SchemeStageService.SchemeStageDelete
   */
  schemeStageDelete: {
    methodKind: "unary";
    input: typeof SchemeStageDeleteRequestSchema;
    output: typeof SchemeStageDeleteResponseSchema;
  },
}>;

