// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file enum/feedback.enum.proto (package contract.ver.enum, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file enum/feedback.enum.proto.
 */
export const file_enum_feedback_enum = /*@__PURE__*/
  fileDesc("ChhlbnVtL2ZlZWRiYWNrLmVudW0ucHJvdG8SEWNvbnRyYWN0LnZlci5lbnVtKtYBCg5GZWVkYmFja0FjdGlvbhIfChtGRUVEQkFDS19BQ1RJT05fVU5TUEVDSUZJRUQQABIXChNGRUVEQkFDS19BQ1RJT05fRklYEAESFwoTRkVFREJBQ0tfQUNUSU9OX0FERBACEhoKFkZFRURCQUNLX0FDVElPTl9DSEFOR0UQAxIaChZGRUVEQkFDS19BQ1RJT05fUkVNT1ZFEAQSHAoYRkVFREJBQ0tfQUNUSU9OX1FVRVNUSU9OEAUSGwoXRkVFREJBQ0tfQUNUSU9OX0FQUFJPVkUQBiqFAQoORmVlZGJhY2tTdGF0dXMSHwobRkVFREJBQ0tfU1RBVFVTX1VOU1BFQ0lGSUVEEAASFwoTRkVFREJBQ0tfU1RBVFVTX05FVxABEh8KG0ZFRURCQUNLX1NUQVRVU19JTl9QUk9HUkVTUxACEhgKFEZFRURCQUNLX1NUQVRVU19ET05FEANCsAEKFWNvbS5jb250cmFjdC52ZXIuZW51bUIRRmVlZGJhY2tFbnVtUHJvdG9QAVoeZHZnbXUvdmVyL2NvbnRyYWN0L2dlbi9nby9lbnVtogIDQ1ZFqgIRQ29udHJhY3QuVmVyLkVudW3KAhFDb250cmFjdFxWZXJcRW51beICHUNvbnRyYWN0XFZlclxFbnVtXEdQQk1ldGFkYXRh6gITQ29udHJhY3Q6OlZlcjo6RW51bWIGcHJvdG8z");

/**
 * Describes the enum contract.ver.enum.FeedbackAction.
 */
export const FeedbackActionSchema = /*@__PURE__*/
  enumDesc(file_enum_feedback_enum, 0);

/**
 * What the customer asks us to do.
 *
 * @generated from enum contract.ver.enum.FeedbackAction
 */
export const FeedbackAction = /*@__PURE__*/
  tsEnum(FeedbackActionSchema);

/**
 * Describes the enum contract.ver.enum.FeedbackStatus.
 */
export const FeedbackStatusSchema = /*@__PURE__*/
  enumDesc(file_enum_feedback_enum, 1);

/**
 * Where the team is with this piece of feedback.
 *
 * @generated from enum contract.ver.enum.FeedbackStatus
 */
export const FeedbackStatus = /*@__PURE__*/
  tsEnum(FeedbackStatusSchema);

