// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file enum/feedback.enum.proto (package contract.ver.enum, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file enum/feedback.enum.proto.
 */
export declare const file_enum_feedback_enum: GenFile;

/**
 * What the customer asks us to do.
 *
 * @generated from enum contract.ver.enum.FeedbackAction
 */
export enum FeedbackAction {
  /**
   * @generated from enum value: FEEDBACK_ACTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: FEEDBACK_ACTION_FIX = 1;
   */
  FIX = 1,

  /**
   * @generated from enum value: FEEDBACK_ACTION_ADD = 2;
   */
  ADD = 2,

  /**
   * @generated from enum value: FEEDBACK_ACTION_CHANGE = 3;
   */
  CHANGE = 3,

  /**
   * @generated from enum value: FEEDBACK_ACTION_REMOVE = 4;
   */
  REMOVE = 4,

  /**
   * @generated from enum value: FEEDBACK_ACTION_QUESTION = 5;
   */
  QUESTION = 5,

  /**
   * @generated from enum value: FEEDBACK_ACTION_APPROVE = 6;
   */
  APPROVE = 6,
}

/**
 * Describes the enum contract.ver.enum.FeedbackAction.
 */
export declare const FeedbackActionSchema: GenEnum<FeedbackAction>;

/**
 * Where the team is with this piece of feedback.
 *
 * @generated from enum contract.ver.enum.FeedbackStatus
 */
export enum FeedbackStatus {
  /**
   * @generated from enum value: FEEDBACK_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: FEEDBACK_STATUS_NEW = 1;
   */
  NEW = 1,

  /**
   * @generated from enum value: FEEDBACK_STATUS_IN_PROGRESS = 2;
   */
  IN_PROGRESS = 2,

  /**
   * @generated from enum value: FEEDBACK_STATUS_DONE = 3;
   */
  DONE = 3,
}

/**
 * Describes the enum contract.ver.enum.FeedbackStatus.
 */
export declare const FeedbackStatusSchema: GenEnum<FeedbackStatus>;

