// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file enum/journal.enum.proto (package contract.ver.enum, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file enum/journal.enum.proto.
 */
export const file_enum_journal_enum = /*@__PURE__*/
  fileDesc("ChdlbnVtL2pvdXJuYWwuZW51bS5wcm90bxIRY29udHJhY3QudmVyLmVudW0qxQEKDFdvcmtDYXRlZ29yeRIdChlXT1JLX0NBVEVHT1JZX1VOU1BFQ0lGSUVEEAASFQoRV09SS19DQVRFR09SWV9ERVYQARIWChJXT1JLX0NBVEVHT1JZX0RPQ1MQAhIZChVXT1JLX0NBVEVHT1JZX1RFU1RJTkcQAxIYChRXT1JLX0NBVEVHT1JZX0RFUExPWRAEEhkKFVdPUktfQ0FURUdPUllfTUVFVElORxAFEhcKE1dPUktfQ0FURUdPUllfT1RIRVIQBkKvAQoVY29tLmNvbnRyYWN0LnZlci5lbnVtQhBKb3VybmFsRW51bVByb3RvUAFaHmR2Z211L3Zlci9jb250cmFjdC9nZW4vZ28vZW51baICA0NWRaoCEUNvbnRyYWN0LlZlci5FbnVtygIRQ29udHJhY3RcVmVyXEVudW3iAh1Db250cmFjdFxWZXJcRW51bVxHUEJNZXRhZGF0YeoCE0NvbnRyYWN0OjpWZXI6OkVudW1iBnByb3RvMw");

/**
 * Describes the enum contract.ver.enum.WorkCategory.
 */
export const WorkCategorySchema = /*@__PURE__*/
  enumDesc(file_enum_journal_enum, 0);

/**
 * @generated from enum contract.ver.enum.WorkCategory
 */
export const WorkCategory = /*@__PURE__*/
  tsEnum(WorkCategorySchema);

