// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file enum/journal.enum.proto (package contract.ver.enum, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file enum/journal.enum.proto.
 */
export declare const file_enum_journal_enum: GenFile;

/**
 * @generated from enum contract.ver.enum.WorkCategory
 */
export enum WorkCategory {
  /**
   * @generated from enum value: WORK_CATEGORY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: WORK_CATEGORY_DEV = 1;
   */
  DEV = 1,

  /**
   * @generated from enum value: WORK_CATEGORY_DOCS = 2;
   */
  DOCS = 2,

  /**
   * @generated from enum value: WORK_CATEGORY_TESTING = 3;
   */
  TESTING = 3,

  /**
   * @generated from enum value: WORK_CATEGORY_DEPLOY = 4;
   */
  DEPLOY = 4,

  /**
   * @generated from enum value: WORK_CATEGORY_MEETING = 5;
   */
  MEETING = 5,

  /**
   * @generated from enum value: WORK_CATEGORY_OTHER = 6;
   */
  OTHER = 6,
}

/**
 * Describes the enum contract.ver.enum.WorkCategory.
 */
export declare const WorkCategorySchema: GenEnum<WorkCategory>;

