// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file enum/scheme.enum.proto (package contract.ver.enum, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file enum/scheme.enum.proto.
 */
export declare const file_enum_scheme_enum: GenFile;

/**
 * Where a scheme stage is.
 *
 * @generated from enum contract.ver.enum.SchemeStageStatus
 */
export enum SchemeStageStatus {
  /**
   * @generated from enum value: SCHEME_STAGE_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SCHEME_STAGE_STATUS_PLANNED = 1;
   */
  PLANNED = 1,

  /**
   * @generated from enum value: SCHEME_STAGE_STATUS_IN_PROGRESS = 2;
   */
  IN_PROGRESS = 2,

  /**
   * @generated from enum value: SCHEME_STAGE_STATUS_DONE = 3;
   */
  DONE = 3,
}

/**
 * Describes the enum contract.ver.enum.SchemeStageStatus.
 */
export declare const SchemeStageStatusSchema: GenEnum<SchemeStageStatus>;

