// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file enum/scheme.enum.proto (package contract.ver.enum, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file enum/scheme.enum.proto.
 */
export const file_enum_scheme_enum = /*@__PURE__*/
  fileDesc("ChZlbnVtL3NjaGVtZS5lbnVtLnByb3RvEhFjb250cmFjdC52ZXIuZW51bSqcAQoRU2NoZW1lU3RhZ2VTdGF0dXMSIwofU0NIRU1FX1NUQUdFX1NUQVRVU19VTlNQRUNJRklFRBAAEh8KG1NDSEVNRV9TVEFHRV9TVEFUVVNfUExBTk5FRBABEiMKH1NDSEVNRV9TVEFHRV9TVEFUVVNfSU5fUFJPR1JFU1MQAhIcChhTQ0hFTUVfU1RBR0VfU1RBVFVTX0RPTkUQA0KuAQoVY29tLmNvbnRyYWN0LnZlci5lbnVtQg9TY2hlbWVFbnVtUHJvdG9QAVoeZHZnbXUvdmVyL2NvbnRyYWN0L2dlbi9nby9lbnVtogIDQ1ZFqgIRQ29udHJhY3QuVmVyLkVudW3KAhFDb250cmFjdFxWZXJcRW51beICHUNvbnRyYWN0XFZlclxFbnVtXEdQQk1ldGFkYXRh6gITQ29udHJhY3Q6OlZlcjo6RW51bWIGcHJvdG8z");

/**
 * Describes the enum contract.ver.enum.SchemeStageStatus.
 */
export const SchemeStageStatusSchema = /*@__PURE__*/
  enumDesc(file_enum_scheme_enum, 0);

/**
 * Where a scheme stage is.
 *
 * @generated from enum contract.ver.enum.SchemeStageStatus
 */
export const SchemeStageStatus = /*@__PURE__*/
  tsEnum(SchemeStageStatusSchema);

