// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file enum/location.enum.proto (package contract.tickets.enum, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file enum/location.enum.proto.
 */
export const file_enum_location_enum: GenFile = /*@__PURE__*/
  fileDesc("ChhlbnVtL2xvY2F0aW9uLmVudW0ucHJvdG8SFWNvbnRyYWN0LnRpY2tldHMuZW51bSKeAQoSTG9jYXRpb25Db21tb25UeXBlEjwKCGJ1aWxkaW5nGAEgASgOMiguY29udHJhY3QudGlja2V0cy5lbnVtLkxvY2F0aW9uQnVpbGRUeXBlSAASQQoJZG9ybWl0b3J5GAIgASgOMiwuY29udHJhY3QudGlja2V0cy5lbnVtLkxvY2F0aW9uRG9ybWl0b3J5VHlwZUgAQgcKBXBsYWNlKqIBChFMb2NhdGlvbkJ1aWxkVHlwZRIeChpMT0NBVElPTl9CVUlMRF9VTlNQRUNJRklFRBAAEhgKFExPQ0FUSU9OX0JVSUxEX0ZJUlNUEAESGQoVTE9DQVRJT05fQlVJTERfU0VDT05EEAISGAoUTE9DQVRJT05fQlVJTERfVEhJUkQQAxIeChpMT0NBVElPTl9CVUlMRF9TVFVEWV9DTEFTUxAEKqsBChVMb2NhdGlvbkRvcm1pdG9yeVR5cGUSJwojTE9DQVRJT05fRE9STUlUT1JZX1RZUEVfVU5TUEVDSUZJRUQQABIiCh5MT0NBVElPTl9ET1JNSVRPUllfVFlQRV9TRUNPTkQQARIhCh1MT0NBVElPTl9ET1JNSVRPUllfVFlQRV9USElSRBACEiIKHkxPQ0FUSU9OX0RPUk1JVE9SWV9UWVBFX0ZPVVJUSBADQsgBChljb20uY29udHJhY3QudGlja2V0cy5lbnVtQhFMb2NhdGlvbkVudW1Qcm90b1ABWiJkdmdtdS90aWNrZXRzL2NvbnRyYWN0L2dlbi9nby9lbnVtogIDQ1RFqgIVQ29udHJhY3QuVGlja2V0cy5FbnVtygIVQ29udHJhY3RcVGlja2V0c1xFbnVt4gIhQ29udHJhY3RcVGlja2V0c1xFbnVtXEdQQk1ldGFkYXRh6gIXQ29udHJhY3Q6OlRpY2tldHM6OkVudW1iBnByb3RvMw");

/**
 * @generated from message contract.tickets.enum.LocationCommonType
 */
export type LocationCommonType = Message<"contract.tickets.enum.LocationCommonType"> & {
  /**
   * @generated from oneof contract.tickets.enum.LocationCommonType.place
   */
  place: {
    /**
     * @generated from field: contract.tickets.enum.LocationBuildType building = 1;
     */
    value: LocationBuildType;
    case: "building";
  } | {
    /**
     * @generated from field: contract.tickets.enum.LocationDormitoryType dormitory = 2;
     */
    value: LocationDormitoryType;
    case: "dormitory";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message contract.tickets.enum.LocationCommonType.
 * Use `create(LocationCommonTypeSchema)` to create a new message.
 */
export const LocationCommonTypeSchema: GenMessage<LocationCommonType> = /*@__PURE__*/
  messageDesc(file_enum_location_enum, 0);

/**
 * @generated from enum contract.tickets.enum.LocationBuildType
 */
export enum LocationBuildType {
  /**
   * @generated from enum value: LOCATION_BUILD_UNSPECIFIED = 0;
   */
  LOCATION_BUILD_UNSPECIFIED = 0,

  /**
   * @generated from enum value: LOCATION_BUILD_FIRST = 1;
   */
  LOCATION_BUILD_FIRST = 1,

  /**
   * @generated from enum value: LOCATION_BUILD_SECOND = 2;
   */
  LOCATION_BUILD_SECOND = 2,

  /**
   * @generated from enum value: LOCATION_BUILD_THIRD = 3;
   */
  LOCATION_BUILD_THIRD = 3,

  /**
   * @generated from enum value: LOCATION_BUILD_STUDY_CLASS = 4;
   */
  LOCATION_BUILD_STUDY_CLASS = 4,
}

/**
 * Describes the enum contract.tickets.enum.LocationBuildType.
 */
export const LocationBuildTypeSchema: GenEnum<LocationBuildType> = /*@__PURE__*/
  enumDesc(file_enum_location_enum, 0);

/**
 * @generated from enum contract.tickets.enum.LocationDormitoryType
 */
export enum LocationDormitoryType {
  /**
   * @generated from enum value: LOCATION_DORMITORY_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: LOCATION_DORMITORY_TYPE_SECOND = 1;
   */
  SECOND = 1,

  /**
   * @generated from enum value: LOCATION_DORMITORY_TYPE_THIRD = 2;
   */
  THIRD = 2,

  /**
   * @generated from enum value: LOCATION_DORMITORY_TYPE_FOURTH = 3;
   */
  FOURTH = 3,
}

/**
 * Describes the enum contract.tickets.enum.LocationDormitoryType.
 */
export const LocationDormitoryTypeSchema: GenEnum<LocationDormitoryType> = /*@__PURE__*/
  enumDesc(file_enum_location_enum, 1);

