// @generated by protoc-gen-es v2.12.1 with parameter "target=ts"
// @generated from file enum/ticket.enum.proto (package contract.tickets.enum, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file enum/ticket.enum.proto.
 */
export const file_enum_ticket_enum: GenFile = /*@__PURE__*/
  fileDesc("ChZlbnVtL3RpY2tldC5lbnVtLnByb3RvEhVjb250cmFjdC50aWNrZXRzLmVudW0qPgoKVGlja2V0VHlwZRIXChNUSUNLRVRfVFlQRV9VTktOT1dOEAASFwoTVElDS0VUX1RZUEVfUExVTUJFUhABKnwKDFRpY2tldFN0YXR1cxIZChVUSUNLRVRfU1RBVFVTX1VOS05PV04QABIZChVUSUNLRVRfU1RBVFVTX1BFTkRJTkcQARIaChZUSUNLRVRfU1RBVFVTX0FQUFJPVkVEEAISGgoWVElDS0VUX1NUQVRVU19SRUpFQ1RFRBADQsYBChljb20uY29udHJhY3QudGlja2V0cy5lbnVtQg9UaWNrZXRFbnVtUHJvdG9QAVoiZHZnbXUvdGlja2V0cy9jb250cmFjdC9nZW4vZ28vZW51baICA0NURaoCFUNvbnRyYWN0LlRpY2tldHMuRW51bcoCFUNvbnRyYWN0XFRpY2tldHNcRW51beICIUNvbnRyYWN0XFRpY2tldHNcRW51bVxHUEJNZXRhZGF0YeoCF0NvbnRyYWN0OjpUaWNrZXRzOjpFbnVtYgZwcm90bzM");

/**
 * @generated from enum contract.tickets.enum.TicketType
 */
export enum TicketType {
  /**
   * @generated from enum value: TICKET_TYPE_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: TICKET_TYPE_PLUMBER = 1;
   */
  PLUMBER = 1,
}

/**
 * Describes the enum contract.tickets.enum.TicketType.
 */
export const TicketTypeSchema: GenEnum<TicketType> = /*@__PURE__*/
  enumDesc(file_enum_ticket_enum, 0);

/**
 * @generated from enum contract.tickets.enum.TicketStatus
 */
export enum TicketStatus {
  /**
   * @generated from enum value: TICKET_STATUS_UNKNOWN = 0;
   */
  UNKNOWN = 0,

  /**
   * @generated from enum value: TICKET_STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: TICKET_STATUS_APPROVED = 2;
   */
  APPROVED = 2,

  /**
   * @generated from enum value: TICKET_STATUS_REJECTED = 3;
   */
  REJECTED = 3,
}

/**
 * Describes the enum contract.tickets.enum.TicketStatus.
 */
export const TicketStatusSchema: GenEnum<TicketStatus> = /*@__PURE__*/
  enumDesc(file_enum_ticket_enum, 1);

