syntax = "proto3";

package contract.tickets.service;

import "entity/ticket.entity.proto";
import "enum/ticket.enum.proto";
import "enum/location.enum.proto";
import "google/protobuf/timestamp.proto";

option go_package = "service;service_pb";

service TicketDormitoryService {
    rpc TicketDormitoryByID (TicketDormitoryByIDRequest) returns (TicketDormitoryByIDResponse);
    rpc TicketDormitoryFetch (TicketDormitoryFetchRequest) returns (TicketDormitoryFetchResponse);
    rpc TicketDormitoryCreate (TicketDormitoryCreateRequest) returns (TicketDormitoryCreateResponse);
    rpc TicketDormitoryChangeStatus (TicketDormitoryChangeStatusRequest) returns (TicketDormitoryChangeStatusResponse);
}

message TicketDormitoryByIDRequest {
    int64 id = 1;
}

message TicketDormitoryByIDResponse {
    contract.tickets.entity.TicketDormitory entity = 1;
}

message TicketDormitoryFetchRequest {
    optional int64 user_id = 1;
    optional int32 room = 2;
    optional contract.tickets.enum.LocationDormitoryType location = 3;
    optional contract.tickets.enum.TicketType type = 4;
    optional contract.tickets.enum.TicketStatus status = 5;
    optional google.protobuf.Timestamp start_date = 6;
    optional google.protobuf.Timestamp end_date = 7;
}

message TicketDormitoryFetchResponse {
    repeated contract.tickets.entity.TicketDormitory tickets = 1;
}

message TicketDormitoryCreateRequest {
    int64 user_id = 1;
    int32 room = 2;
    contract.tickets.enum.LocationDormitoryType location = 3;
    string comment = 4;
    contract.tickets.enum.TicketType type = 5;
}

message TicketDormitoryCreateResponse {
    int64 id = 1;
    bool success = 2;
    string message = 3;
}

message TicketDormitoryChangeStatusRequest {
    int64 id = 1;
    contract.tickets.enum.TicketStatus new_status = 2;
}

message TicketDormitoryChangeStatusResponse {
    int64 id = 1;
    bool success = 2;
    string message = 3;
}

service TicketBuildService {
    rpc TicketBuildByID (TicketBuildByIDRequest) returns (TicketBuildByIDResponse);
    rpc TicketBuildFetch (TicketBuildFetchRequest) returns (TicketBuildFetchResponse);
    rpc TicketBuildCreate (TicketBuildCreateRequest) returns (TicketBuildCreateResponse);
    rpc TicketBuildChangeStatus (TicketBuildChangeStatusRequest) returns (TicketBuildChangeStatusResponse);
}

message TicketBuildByIDRequest {
    int64 id = 1;
}

message TicketBuildByIDResponse {
    contract.tickets.entity.TicketBuild entity = 1;
}

message TicketBuildFetchRequest {
    optional int64 user_id = 1;
    optional int32 room = 2;
    optional contract.tickets.enum.LocationBuildType location = 3;
    optional contract.tickets.enum.TicketType type = 4;
    optional contract.tickets.enum.TicketStatus status = 5;
    optional google.protobuf.Timestamp start_date = 6;
    optional google.protobuf.Timestamp end_date = 7;
}

message TicketBuildFetchResponse {
    repeated contract.tickets.entity.TicketBuild tickets = 1;
}

message TicketBuildCreateRequest {
    int64 user_id = 1;
    int32 room = 2;
    contract.tickets.enum.LocationBuildType location = 3;
    string comment = 4;
    contract.tickets.enum.TicketType type = 5;
}

message TicketBuildCreateResponse {
    int64 id = 1;
    bool success = 2;
    string message = 3;
}

message TicketBuildChangeStatusRequest {
    int64 id = 1;
    contract.tickets.enum.TicketStatus new_status = 2;
}

message TicketBuildChangeStatusResponse {
    int64 id = 1;
    bool success = 2;
    string message = 3;
}
