// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file entity/feedback.entity.proto (package contract.ver.entity, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { FeedbackAction, FeedbackStatus } from "../enum/feedback.enum_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file entity/feedback.entity.proto.
 */
export declare const file_entity_feedback_entity: GenFile;

/**
 * Feedback is a customer's comment on one version of one site.
 *
 * @generated from message contract.ver.entity.Feedback
 */
export declare type Feedback = Message<"contract.ver.entity.Feedback"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * The site and its documentation version the comment is about.
   *
   * @generated from field: string site_slug = 2;
   */
  siteSlug: string;

  /**
   * @generated from field: string site_name = 3;
   */
  siteName: string;

  /**
   * @generated from field: string version_id = 4;
   */
  versionId: string;

  /**
   * @generated from field: string version_label = 5;
   */
  versionLabel: string;

  /**
   * @generated from field: string author_name = 6;
   */
  authorName: string;

  /**
   * Normalized: +7XXXXXXXXXX.
   *
   * @generated from field: string phone = 7;
   */
  phone: string;

  /**
   * @generated from field: contract.ver.enum.FeedbackAction action = 8;
   */
  action: FeedbackAction;

  /**
   * @generated from field: string comment = 9;
   */
  comment: string;

  /**
   * @generated from field: contract.ver.enum.FeedbackStatus status = 10;
   */
  status: FeedbackStatus;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 11;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 12;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message contract.ver.entity.Feedback.
 * Use `create(FeedbackSchema)` to create a new message.
 */
export declare const FeedbackSchema: GenMessage<Feedback>;

