// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file entity/journal.entity.proto (package contract.ver.entity, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import type { WorkCategory } from "../enum/journal.enum_pb";

/**
 * Describes the file entity/journal.entity.proto.
 */
export declare const file_entity_journal_entity: GenFile;

/**
 * @generated from message contract.ver.entity.Journal
 */
export declare type Journal = Message<"contract.ver.entity.Journal"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string slug = 2;
   */
  slug: string;

  /**
   * @generated from field: string employee = 3;
   */
  employee: string;

  /**
   * @generated from field: string role = 4;
   */
  role: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message contract.ver.entity.Journal.
 * Use `create(JournalSchema)` to create a new message.
 */
export declare const JournalSchema: GenMessage<Journal>;

/**
 * @generated from message contract.ver.entity.WorkEntry
 */
export declare type WorkEntry = Message<"contract.ver.entity.WorkEntry"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int64 journal_id = 2;
   */
  journalId: bigint;

  /**
   * @generated from field: string date = 3;
   */
  date: string;

  /**
   * @generated from field: string site_slug = 4;
   */
  siteSlug: string;

  /**
   * @generated from field: contract.ver.enum.WorkCategory category = 5;
   */
  category: WorkCategory;

  /**
   * @generated from field: string title = 6;
   */
  title: string;

  /**
   * @generated from field: string details = 7;
   */
  details: string;

  /**
   * @generated from field: repeated string steps = 8;
   */
  steps: string[];

  /**
   * @generated from field: string result = 9;
   */
  result: string;

  /**
   * @generated from field: double hours = 10;
   */
  hours: number;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 11;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 12;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message contract.ver.entity.WorkEntry.
 * Use `create(WorkEntrySchema)` to create a new message.
 */
export declare const WorkEntrySchema: GenMessage<WorkEntry>;

