// @generated by protoc-gen-es v2.12.1 with parameter "target=js+dts"
// @generated from file entity/scheme.entity.proto (package contract.ver.entity, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { SchemeStageStatus } from "../enum/scheme.enum_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file entity/scheme.entity.proto.
 */
export declare const file_entity_scheme_entity: GenFile;

/**
 * SchemeStage is one step of the work plan kept next to a project's scheme:
 * what has to be done and by when.
 *
 * @generated from message contract.ver.entity.SchemeStage
 */
export declare type SchemeStage = Message<"contract.ver.entity.SchemeStage"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * The project and the scheme (its `id` in the project data) the stage belongs to.
   *
   * @generated from field: string site_slug = 2;
   */
  siteSlug: string;

  /**
   * @generated from field: string scheme_id = 3;
   */
  schemeId: string;

  /**
   * @generated from field: string title = 4;
   */
  title: string;

  /**
   * @generated from field: string details = 5;
   */
  details: string;

  /**
   * ISO days, YYYY-MM-DD; empty when not set.
   *
   * @generated from field: string start_date = 6;
   */
  startDate: string;

  /**
   * @generated from field: string due_date = 7;
   */
  dueDate: string;

  /**
   * @generated from field: contract.ver.enum.SchemeStageStatus status = 8;
   */
  status: SchemeStageStatus;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 9;
   */
  createdAt?: Timestamp | undefined;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 10;
   */
  updatedAt?: Timestamp | undefined;
};

/**
 * Describes the message contract.ver.entity.SchemeStage.
 * Use `create(SchemeStageSchema)` to create a new message.
 */
export declare const SchemeStageSchema: GenMessage<SchemeStage>;

